name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-04"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjNiOWM1OWYtMzY2NS00YjNjLTk1YzUtZmYwZDk5OWE5NzI0IiwidGVuYW50X2lkIjoiYjM5MWMzMmRiYTMwYjJiMjg4NDY0NDM5ZDczMDJmZjVmNzRhNDVmZTk0YmQ5NjYyNDdlMjU4NWEwMWE2YmFjMSIsImludGVybmFsX3NlY3JldCI6IjIzNDI2MTJkLWQ2YWEtNDMxMi05NThjLWUzMzU2OTEyN2ExZiJ9.hWo8sJYunN07SyzoRdv374fT_WTW1dLIisM6HNguxI4"

JWT_SECRET="LUFFY"
